config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :folders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accessibility.rb
class Accessibility < ApplicationRecord
  belongs_to :owner, class_name: :User, foreign_key: :owner_id
  belongs_to :user
  belongs_to :folder

  before_save :check_owner

  private
  def check_owner
    raise 'forbidden: not folder owner' unless self.folder.owner_id?(self.owner.id)
  end

end

app/models/app_file.rb
class AppFile < ApplicationRecord
  belongs_to :user
  belongs_to :folder

  def full_path
    self.folder.full_path + '/' + self.name
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  has_many :app_files, dependent: :destroy
  has_many :accessibilities, dependent: :destroy

  has_ancestry cache_depth: true, touch: true

  before_save :inherit_user

  def full_path
    self.path.map(&:name).join('/')
  end

  def move_into(folder_id)
    target_folder = self.user.folders.find_by(id: folder_id)
    return nil if target_folder.nil?

    folders_to_move = self.children.to_a
    folders_to_move << self

    new_path = target_folder.ancestry + '/' + target_folder.id.to_s
    old_path = self.ancestry

    folders_to_move.each do |folder|
      folder.ancestry = folder.ancestry.sub(old_path, new_path)
      folder.save!
    end

    return folders_to_move
  end

  def can_user_read?(user_id)
    return true if owner_id?(user_id)
    acc = get_accessibility_to_apply(user_id)
    return acc.nil? ? false : acc.can_read
  end

  def can_user_write?(user_id)
    return true if owner_id?(user_id)
    acc = get_accessibility_to_apply(user_id)
    return acc.nil? ? false : acc.can_write
  end

  def owner_id?(user_id)
    return self.user.id == user_id
  end

  private
  def inherit_user
    self.user = self.root.user if self.user.nil?
  end

  def get_accessibility_to_apply(user_id)
    accessibility_to_apply = nil
    acc = :accessibilities
    folders = self.path.includes(acc).where(acc => { user_id: user_id })
    return folders.last.accessibilities.first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :app_files, dependent: :destroy
  has_many :folders, dependent: :destroy
  has_many :allowances, class_name: :Accessibility, foreign_key: :owner_id, dependent: :destroy
  has_many :accessibilities, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :set_folder, only: [:show, :edit, :update, :destroy]

  # GET /folders
  # GET /folders.json
  def index
    @folders = Folder.all
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
  end

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  # GET /folders/1/edit
  def edit
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(folder_params)

    respond_to do |format|
      if @folder.save
        format.html { redirect_to @folder, notice: 'Folder was successfully created.' }
        format.json { render :show, status: :created, location: @folder }
      else
        format.html { render :new }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to folders_url, notice: 'Folder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_folder
      @folder = Folder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def folder_params
      params.require(:folder).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/folders/_form.html.erb
<%= form_for(folder) do |f| %>
  <% if folder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
      <% folder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/folders/edit.html.erb
<h1>Editing Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Show', @folder %> |
<%= link_to 'Back', folders_path %>

app/views/folders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Folders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @folders.each do |folder| %>
      <tr>
        <td><%= folder.name %></td>
        <td><%= link_to 'Show', folder %></td>
        <td><%= link_to 'Edit', edit_folder_path(folder) %></td>
        <td><%= link_to 'Destroy', folder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Folder', new_folder_path %>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form', folder: @folder %>

<%= link_to 'Back', folders_path %>

app/views/folders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @folder.name %>
</p>

<%= link_to 'Edit', edit_folder_path(@folder) %> |
<%= link_to 'Back', folders_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FolderDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>